name: CI
on: [push] 
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel


jobs:
  # This workflow contains a single job called "build"
  build:
    name: flutter build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11"
      FLUTTER_VERSION: "2.10.3"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.4"         
      - run: flutter pub get
      - run: flutter test